### ISSUE TITLE
一些关于论文的小问题

### ISSUE THREAD

**Issue by seanM29** [bronyayang/Law_of_Vision_Representation_in_MLLMs#2]
非常棒的工作！感谢作者的分享，有几个小问题想问下哈
1. 算A的时候，为什么要算出所有图片对的相似度后（一个N*N的矩阵），再算max？我理解因为图片是同一张，直接算对应图片的clip 特征和候选视觉encode的特征相似度就可以了？
2. 好奇AC POLICY有 reacall @1的结果吗？方便展示吗？
3. table 1的random 那一行怎么理解呢？ AC POLICY的图片是多个数据集（mmb,mme....）混合在一起随机选的吗？那random setting的recall@3上评估的是哪个数据集呢？

**Comment by bronyayang** [comment]
Hi,

Thanks for liking our work and your patience.

> 1. 算A的时候，为什么要算出所有图片对的相似度后（一个N*N的矩阵），再算max？我理解因为图片是同一张，直接算对应图片的clip 特征和候选视觉encode的特征相似度就可以了？

The equation is a bit of confusing, and we will fix it in the next version. The matrix is the result of all pairs of embedding vectors **within the same image**, just like an attention matrix. We then do some max and average to get a number of A score of this image. In the end, the score is averaged across all images. Basically, this is the same as what you said here. The code of computing A score is [here](https://github.com/bronyayang/Law_of_Vision_Representation_in_MLLMs/blob/master/A_score/compute.py).

> 好奇AC POLICY有 reacall @1的结果吗？方便展示吗？

AC Policy gives improvement for all Recall@1, Recall@2, Recall@3 as shown in the below figures. However, since the law is not a perfect fit (95% in R^2) due to A and C design, and some performance perturbation can occur during training, it is never advised to run only the top-1 vision representation predicted. (Also, note that our "best vision representation ground truth" in testing this experiment is subjected to performance perturbation, since we only train each MLLM once.). Although we advertised the number of finetuning, the additional significance of AC Policy is that **it gives an order to the vision representation you should run**. At the 3rd run (Recall@3), the confidence is proven high that you reached the optimal vision representation.

<img width="200" alt="Screenshot 2024-09-15 at 1 40 52 PM" src="https://github.com/user-attachments/assets/067bce06-067b-486f-a17b-2ad48c0384d4"> This shows the the Recall@1 for MME. 


<img width="200" alt="Screenshot 2024-09-15 at 1 49 04 PM" src="https://github.com/user-attachments/assets/57f8bc39-dec7-452b-a1d8-2f103e3ee956"> This shows the the Recall@1 for OKVQA. 


> table 1的random 那一行怎么理解呢？ AC POLICY的图片是多个数据集（mmb,mme....）混合在一起随机选的吗？那random setting的recall@3上评估的是哪个数据集呢？

Table 1 "Random" means the average Recall@3 across all benchmark with randomly selecting encoders. Although we average across benchmarks, the random result is the same for every benchmark anyway. You can see Table 3 for detailed visualization. Here, Recall@3 is the same as Recall@1. The row means you need to run 12 fintuning out of 13 to include the best encoder 92% of the time. AC policy fits one policy for every benchmark.

**Comment by tangli-udel** [comment]
Hi,

Great work and thank you for the answers.

Following question 1, "The matrix is the result of all pairs of embedding vectors within the same image, just like an attention matrix." Do the embedding vectors here mean embeddings of each image patch? If so, why do we calculate the similarity between all possible pairs of patch embedding? Doesn't it make more sense to just calculate the similarity between the pairs of patch embeddings at the same position?
